name: portfolio
description: "My Porfolio"
publish_to: 'none' # Remove this line if you wish to publish to pub.dev

version: 1.0.0+1

environment:
  sdk: '>=3.3.4 <4.0.0'

dependencies:
  flutter:
    sdk: flutter


  cupertino_icons: ^1.0.6
  scrollable_positioned_list: ^0.3.5
  rive_animated_icon: ^2.0.0
  url_launcher: ^6.3.0
  google_fonts: ^6.2.1
  simple_icons: ^10.1.3
  provider: ^6.1.2
  shared_preferences: ^2.2.3
  responsive_framework: ^1.5.1
  widget_and_text_animator: ^1.1.5
  font_awesome_flutter:
  infinite_carousel: ^1.1.1
  flutter_carousel_widget: ^3.0.1


flutter_svg:

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^4.0.0

flutter:
  uses-material-design: true
  assets:
    - assets/images/svg/
    - assets/images/
  fonts:
    - family: Google Sans
      fonts:
        - asset: assets/fonts/product_sans_regular.ttf
        - asset: assets/fonts/product_sans_bold.ttf
          weight: 700
        - asset: assets/fonts/product_sans_italic.ttf
          style: italic
    - family: Roboto
      fonts:
        - asset: assets/fonts/roboto_regular.ttf
        - asset: assets/fonts/roboto_bold.ttf
          weight: 700
        - asset: assets/fonts/roboto_italic.ttf
          style: italic
